#include "factory_ui_visage/Fonts.h"

// Generated by add_embedded_resources() in ui/visage/CMakeLists.txt: turns the
// .ttf files into C++ byte arrays under namespace factory_ui_visage::fonts.
#include "embedded/factory_ui_visage_fonts.h"

namespace factory_ui_visage
{
    // The ONE place that names concrete font bytes — see Fonts.h for how to swap.
    visage::Font regularFont (float sizePx)
    {
        return visage::Font (sizePx, factory_ui_visage::fonts::Quicksand_Regular_ttf);
    }

    visage::Font boldFont (float sizePx)
    {
        return visage::Font (sizePx, factory_ui_visage::fonts::Quicksand_Bold_ttf);
    }
}
