#include "factory_ui_visage/Fonts.h"

// Generated by add_embedded_resources() in ui/visage/CMakeLists.txt: turns the
// .ttf files in ui/visage/fonts/ into C++ byte arrays under namespace
// factory_ui_visage::fonts (symbol == filename with '.', ' ', '-' -> '_').
#include "embedded/factory_ui_visage_fonts.h"

#include <cstring>

namespace factory_ui_visage
{
    namespace
    {
        // The ONE place that names concrete font bytes — see Fonts.h to add a face.
        FontFamily g_family = FontFamily::Quicksand;

        const visage::EmbeddedFile& regularBytes()
        {
            switch (g_family)
            {
                case FontFamily::Nunito: return fonts::Nunito_Regular_ttf;
                case FontFamily::MPlus:  return fonts::MPLUSRounded1c_Regular_ttf;
                case FontFamily::Quicksand:
                default:                 return fonts::Quicksand_Regular_ttf;
            }
        }

        const visage::EmbeddedFile& boldBytes()
        {
            switch (g_family)
            {
                case FontFamily::Nunito: return fonts::Nunito_Bold_ttf;
                case FontFamily::MPlus:  return fonts::MPLUSRounded1c_Bold_ttf;
                case FontFamily::Quicksand:
                default:                 return fonts::Quicksand_Bold_ttf;
            }
        }
    } // namespace

    void       setFontFamily (FontFamily family) { g_family = family; }
    FontFamily fontFamily() { return g_family; }

    bool setFontFamilyByName (const char* name)
    {
        if (name == nullptr)
            return false;
        if (std::strcmp (name, "quicksand") == 0) { g_family = FontFamily::Quicksand; return true; }
        if (std::strcmp (name, "nunito")    == 0) { g_family = FontFamily::Nunito;    return true; }
        if (std::strcmp (name, "mplus")     == 0) { g_family = FontFamily::MPlus;     return true; }
        return false;
    }

    const char* fontFamilyName()
    {
        switch (g_family)
        {
            case FontFamily::Nunito: return "nunito";
            case FontFamily::MPlus:  return "mplus";
            case FontFamily::Quicksand:
            default:                 return "quicksand";
        }
    }

    visage::Font regularFont (float sizePx) { return visage::Font (sizePx, regularBytes()); }
    visage::Font boldFont (float sizePx)    { return visage::Font (sizePx, boldBytes()); }
}
