# tatsunari-sounds bootstrap shim (Windows) — published at
# https://6sryusk.com/tatsunarisounds/install.ps1
#
#   irm https://6sryusk.com/tatsunarisounds/install.ps1 | iex
#
# See shim.sh for why this indirection exists: the bootstrap is the one object
# minisign cannot cover, so it is kept tiny and it does nothing but fetch a
# VERSIONED, IMMUTABLE payload and verify its SHA-256 before running it. The pin
# below is generated by tools/promote/bootstrap.py and gated by
# tools/tests/test_bootstrap_pin.py.
#
# Do not add features here. Everything that can live in the verified payload
# must live in the verified payload.

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$Base = 'https://6sryusk.com/tatsunarisounds'

# --- generated pin: do not edit by hand (tools/promote/bootstrap.py) ---
$BootstrapVersion = '1'
$BootstrapSha256  = '71d486279b6ed988bb0d33e26439f0f14d019f99ccde473f7c9d5366409a9122'
# --- end generated pin ---

$PayloadUrl = "$Base/bootstrap/$BootstrapVersion/install.ps1"

# TLS 1.2+ explicitly: Windows PowerShell 5.1 still negotiates TLS 1.0 by default
# on some hosts, and a bootstrap must not be the thing that downgrades.
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

$dir = Join-Path $env:TEMP ("tatsunari-sounds-boot-" + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Force $dir | Out-Null
try {
    $payload = Join-Path $dir 'install.ps1'

    # -MaximumRedirection 0: a redirect is a change of origin we did not agree
    # to. Following one silently is how a bootstrap executes somebody else's
    # script. PowerShell raises on 3xx with this set, which is what we want.
    try {
        $resp = Invoke-WebRequest -UseBasicParsing -Uri $PayloadUrl `
                    -MaximumRedirection 0 -OutFile $payload -PassThru
    } catch {
        throw "Refusing to continue: $PayloadUrl did not return a direct 200 ($($_.Exception.Message)). A redirect or an error here means the bootstrap is not being served as published."
    }
    if ($resp.StatusCode -ne 200) {
        throw "Refusing to continue: $PayloadUrl returned HTTP $($resp.StatusCode)."
    }

    $got = (Get-FileHash -Algorithm SHA256 -Path $payload).Hash.ToLowerInvariant()
    if ($got -ne $BootstrapSha256) {
        throw "SHA-256 mismatch for the bootstrap payload.`n  expected $BootstrapSha256`n  got      $got`nNot executing it. Report this: the published script does not match the pin."
    }

    & $payload @args
} finally {
    Remove-Item -Recurse -Force $dir -ErrorAction SilentlyContinue
}
